import './bootstrap';
import { initNavigation } from './modules/navigation';
import { initFilters } from './modules/filters';
import { initPrediction } from './modules/prediction';
import { initPriceTable } from './modules/price-table';
import { initMovements } from './modules/movements';
import { initCrudAlerts } from './modules/crud-alerts';
import { initConfirmDialog } from './modules/confirm-dialog';
import { initPriceImport } from './modules/price-import';
import { initBulkPriceActions } from './modules/bulk-price-actions';
import { initChartTimeline } from './modules/chart-timeline';
import { initPasswordToggle } from './modules/password-toggle';
import { initInfographicUpload } from './modules/infographic-upload';
import { initInfographicLightbox } from './modules/infographic-lightbox';
import { initMarketComparisonChart } from './modules/market-comparison-chart';
import { initPredictionChart } from './modules/prediction-chart';
import { initMarketPredictionEvaluation } from './modules/market-prediction-evaluation';

initNavigation();
initFilters();
initPrediction();
initPriceTable();
initMovements();
initCrudAlerts();
initConfirmDialog();
initPriceImport();
initBulkPriceActions();
initChartTimeline();
initPasswordToggle();
initInfographicUpload();
initInfographicLightbox();
initMarketComparisonChart();
initPredictionChart();
initMarketPredictionEvaluation();
