@extends('layouts.app')
@section('title','Laporan Harga')
@section('content')
<div class="page feature-page report-page">
 @include('features.page-heading',['eyebrow'=>'DOKUMEN DATA','title'=>'Laporan Harga Komoditas','description'=>'Susun laporan berdasarkan periode, pasar, kategori, dan komoditas lalu unduh sebagai CSV atau simpan sebagai PDF.'])
 @include('master.partials.alerts')
 <section class="panel report-filter"><div class="report-filter-heading"><div><span>FILTER LAPORAN</span><h2>Tentukan data yang akan dicetak</h2></div><a href="{{ route('reports.index') }}">Bersihkan filter</a></div><form method="GET" class="report-filter-grid">
  <label><span>Tanggal mulai</span><input type="date" name="start_date" value="{{ $filters['start_date']??'' }}"></label><label><span>Tanggal akhir</span><input type="date" name="end_date" value="{{ $filters['end_date']??'' }}"></label>
  <label><span>Pasar</span><select name="market"><option value="">Semua pasar</option>@foreach($markets as $market)<option value="{{ $market->id }}" @selected(($filters['market']??null)==$market->id)>{{ $market->name }}</option>@endforeach</select></label>
  <label><span>Kategori</span><select name="category"><option value="">Semua kategori</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(($filters['category']??null)==$category->id)>{{ $category->name }}</option>@endforeach</select></label>
  <label class="report-commodity-filter"><span>Komoditas</span><select name="commodity"><option value="">Semua komoditas</option>@foreach($commodities as $commodity)<option value="{{ $commodity->id }}" @selected(($filters['commodity']??null)==$commodity->id)>{{ $commodity->name }}</option>@endforeach</select></label><button class="primary-button">Terapkan filter</button>
 </form></section>
 <section class="report-summary report-summary-five"><div><span>Baris data</span><strong>{{ number_format($summary->total??0) }}</strong><small>Sesuai filter</small></div><div><span>Jumlah tanggal</span><strong>{{ number_format($summary->dates??0) }}</strong><small>Periode tercakup</small></div><div><span>Rata-rata harga</span><strong>Rp {{ number_format($summary->average_price??0,0,',','.') }}</strong><small>Seluruh pasar terpilih</small></div><div><span>Harga kosong</span><strong>{{ number_format($summary->zero_count??0) }}</strong><small>Nilai 0 tetap dicatat</small></div><div class="report-actions"><a class="report-download" href="{{ route('reports.export',request()->query()) }}">Unduh CSV</a><a class="report-pdf-download" href="{{ route('reports.pdf',request()->query()) }}">Unduh PDF Lengkap</a><small>Semua {{ number_format($summary->total??0) }} data, bukan hanya halaman ini</small></div></section>
 <section class="panel report-table-panel"><div class="panel-head"><div><span class="report-document-label">PRATINJAU DOKUMEN</span><h2>Rincian laporan harga</h2><p>Dibuat {{ now()->translatedFormat('d F Y, H:i') }} WIB</p></div><div class="report-result-count">{{ number_format($summary->total??0) }} data</div></div><div class="table-wrap"><table><thead><tr><th>No</th><th>Tanggal</th><th>Kategori</th><th>Komoditas</th><th>Satuan</th><th>Pasar</th><th>Harga</th><th>Sumber</th></tr></thead><tbody>@forelse($rows as $row)<tr><td>{{ $rows->firstItem()+$loop->index }}</td><td>{{ $row->price_date->translatedFormat('d M Y') }}</td><td>{{ $row->commodity->category->name }}</td><td><strong>{{ $row->commodity->name }}</strong></td><td>{{ $row->commodity->unit }}</td><td>{{ $row->market->name }}</td><td><strong class="report-price {{ $row->price==0?'is-zero':'' }}">Rp {{ number_format($row->price,0,',','.') }}</strong></td><td>{{ $row->source }}</td></tr>@empty<tr><td colspan="8"><div class="empty-state"><strong>Data tidak ditemukan</strong><small>Ubah periode atau pilihan filter laporan.</small></div></td></tr>@endforelse</tbody></table></div>{{ $rows->links('partials.pagination') }}</section>
</div>
@endsection
