<!doctype html>
<html lang="id"><head><meta charset="UTF-8"><style>
@page{margin:25mm 10mm 15mm 10mm}*{box-sizing:border-box}body{font-family:"DejaVu Sans",sans-serif;color:#172b46;font-size:8px;margin:0}.document-header{position:fixed;top:-18mm;left:0;right:0;height:15mm;border-bottom:2px solid #1e63ad}.brand{float:left}.brand-mark{display:inline-block;background:#174f91;color:#fff;border-radius:5px;padding:7px 9px;font-size:13px;font-weight:bold;margin-right:8px}.brand-copy{display:inline-block;vertical-align:middle}.brand-copy strong{display:block;font-size:12px}.brand-copy span{font-size:7px;color:#63738a}.official{float:right;text-align:right}.official strong{display:block;color:#1b5fa7;font-size:9px}.official span{font-size:7px;color:#6e7d91}.document-title{text-align:center;margin:0 0 10px}.document-title h1{font-size:16px;margin:0 0 4px;color:#123b6c}.document-title p{margin:0;color:#66768b}.filter-info{width:100%;border-collapse:separate;border-spacing:5px;margin:0 0 9px}.filter-info td{width:20%;background:#eff5fc;border:1px solid #d9e4f1;border-radius:4px;padding:6px}.filter-info span{display:block;font-size:6px;text-transform:uppercase;color:#74849a;margin-bottom:2px}.filter-info strong{font-size:7px}table.data{width:100%;border-collapse:collapse;table-layout:fixed}table.data thead{display:table-header-group}table.data tr{page-break-inside:avoid}table.data th{background:#174f91;color:#fff;border:1px solid #17477c;padding:6px 4px;font-size:6.5px;text-transform:uppercase}table.data td{border:1px solid #d3dce8;padding:4px;vertical-align:top;line-height:1.35}table.data tbody tr:nth-child(even) td{background:#f7f9fc}.number{text-align:center}.price{text-align:right;font-weight:bold;color:#124f93}.zero{color:#8793a3}.footer-note{margin-top:8px;padding-top:6px;border-top:1px solid #d6dfeb;color:#697a90;font-size:6.5px}.col-no{width:3%}.col-date{width:8%}.col-market{width:13%}.col-category{width:11%}.col-commodity{width:20%}.col-unit{width:7%}.col-price{width:10%}.col-source{width:28%}
</style></head><body>
<header class="document-header"><div class="brand"><span class="brand-mark">MH</span><div class="brand-copy"><strong>Mojokerto Harga</strong><span>Sistem Informasi Perkembangan Harga Bahan Pokok</span></div></div><div class="official"><strong>KABUPATEN MOJOKERTO</strong><span>Laporan data harga komoditas</span></div></header>
<main><div class="document-title"><h1>Laporan Harga Komoditas Kabupaten Mojokerto</h1><p>Dokumen dibuat {{ now()->translatedFormat('d F Y, H:i') }} WIB · {{ number_format($total) }} baris data</p></div>
<table class="filter-info"><tr><td><span>Periode awal</span><strong>{{ isset($filters['start_date'])?\Carbon\Carbon::parse($filters['start_date'])->translatedFormat('d M Y'):'Semua tanggal' }}</strong></td><td><span>Periode akhir</span><strong>{{ isset($filters['end_date'])?\Carbon\Carbon::parse($filters['end_date'])->translatedFormat('d M Y'):'Semua tanggal' }}</strong></td><td><span>Pasar</span><strong>{{ $marketName }}</strong></td><td><span>Kategori</span><strong>{{ $categoryName }}</strong></td><td><span>Komoditas</span><strong>{{ $commodityName }}</strong></td></tr></table>
<table class="data"><thead><tr><th class="col-no">No</th><th class="col-date">Tanggal</th><th class="col-market">Pasar</th><th class="col-category">Kategori</th><th class="col-commodity">Komoditas</th><th class="col-unit">Satuan</th><th class="col-price">Harga</th><th class="col-source">Sumber data</th></tr></thead><tbody>@foreach($rows as $row)<tr><td class="number">{{ $loop->iteration }}</td><td>{{ $row->price_date->format('d/m/Y') }}</td><td>{{ $row->market->name }}</td><td>{{ $row->commodity->category->name }}</td><td><strong>{{ $row->commodity->name }}</strong></td><td>{{ $row->commodity->unit }}</td><td class="price {{ $row->price==0?'zero':'' }}">Rp {{ number_format($row->price,0,',','.') }}</td><td>{{ $row->source }}</td></tr>@endforeach</tbody></table>
<div class="footer-note">Harga bernilai 0 tetap dicantumkan sebagai data kosong sesuai sumber. Dokumen ini memuat seluruh hasil filter dan tidak dibatasi pagination tampilan website.</div></main></body></html>
